### PR TITLE
Fix: AnimationController.dispose() called more than once. on multiple action show

### LINKED ISSUE #132: AnimationController.dispose() called more than once. on multiple action show
my app got freeze when show toastification

i use toastification with context, when i click action and trigger show toastification. (first time ok)
but for next toast, my app got freeze and throw exception

this should be fine, based on flow code i wrote
class AppInfo {
  static error(BuildContext context, String message) {
    toastification.show(
      context: context,
      title: Text(message),
      autoCloseDuration: const Duration(milliseconds: 2500),
      closeButtonShowType: CloseButtonShowType.none,
    );
  }
}

void addNew() {
...
if (xFile.path == '') {
      AppInfo.error(context, 'No Image Selected');
      return;
}
...
}

image

image

 - OS: Web
 - Flutter Version: 3.24.1
 - Toastification Version: 8.2.8

### PR DESCRIPTION
**Pull request by AntonioAEMartins**
**Problem:** `AnimationController.dispose()` was called multiple times, leading to errors.

**Scenarios:**
1. Disposing multiple toasts concurrently.
2. Disposing a single toast with a progress bar.

**Root Cause:**
In the file `toastification_manager.dart`, there was a delay between creating and inserting the `OverlayEntry` and adding the toast to the `_notifications` list.

`
if (_overlayEntry == null) {
    _createNotificationHolder(overlayState);

    // TODO: remove this delay in future updates
    delay = const Duration(milliseconds: 300);
}

Future.delayed(
  delay,
  () {
    _notifications.insert(0, item);

    _listGlobalKey.currentState?.insertItem(
      0,
      duration: _createAnimationDuration(item),
    );
  },
);
`

This delay caused a timing issue, where the toast was being created but not yet added to **_notifications**, while the **OverlayEntry** was removed prematurely in the following code:

`
Future.delayed(
  (removedItem.animationDuration ?? config.animationDuration),
  () {
    if (_notifications.isEmpty) {
      _overlayEntry?.remove();
      _overlayEntry = null;
    }
  },
);
`

Because the toast wasn’t in the list yet, the **OverlayEntry** was removed too early, leading to multiple calls of **AnimationController.dispose()**.

**Solution:**
The solution was to account for the initial delay in the toast creation process when scheduling the removal of the `OverlayEntry`. This ensures that the overlay is only removed after the toast has been properly inserted and displayed:

`
Future.delayed(
  delay + (removedItem.animationDuration ?? config.animationDuration),
  () {
    if (_notifications.isEmpty) {
      _overlayEntry?.remove();
      _overlayEntry = null;
    }
  },
);
`

This synchronization prevents the **AnimationController.dispose()** from being called multiple times.

closes #132 #54

### CODE REVIEW

**Comment by AntonioAEMartins** [comment]
@payam-zahedi I've done my best to explain the changes. The root of the problem is quite complex, as it involves the behavior of the AnimationController and the limitations of Flutter's stack traces. However, the actual code change is relatively straightforward.

I’ve tested the solution and haven't encountered any scenarios where this adjustment negatively impacts existing functionality or usability. Everything seems to work as expected without affecting any previously implemented features.

File: lib/src/core/toastification_manager.dart [hunk 1]
```diff
@@ -27,6 +27,8 @@ class ToastificationManager {
   /// if the list is empty, the overlay entry will be removed
   final List<ToastificationItem> _notifications = [];
 
+  Duration delay = const Duration(milliseconds: 10);
```
Comment (payam-zahedi) [inline lib/src/core/toastification_manager.dart:30]: Creating a class field as delay is not really make sense

When we are creating the overlay in line 60 and we will update this value to 300 milliseconds and we always use that value

Basicity the delay value in every situation is 300 milliseconds 
I'm going to test and see what are the side effects

**Review by payam-zahedi — COMMENTED** [review]
Hey @AntonioAEMartins 

Thank you for your contribution 
And you described your solution well, thanks for that 

And I believe you found the issue 

Just I need to change it a bit and make sure everything is working

**Comment by payam-zahedi** [comment]
@AntonioAEMartins 

I added a commit to solve side effect issues

now we have different delays for creating and removing the overlay 

I tested it a lot, and it seems everything is working fine

https://github.com/user-attachments/assets/c37049de-eb45-470b-bef7-ae59cf1b3073
